Pic 2290
ministryofjustice/court-case-matcher pull request #476
Opened 2022-07-29 12:10 UTC by vb-moj

2022-08-01 13:37 UTC, jhevans requested changes

2022-08-01 13:37 UTC, jhevans commented on src/main/java/uk/gov/justice/probation/courtcasematcher/model/domain/Hearing.java
> +    private final String hearingEventType;
I can't see where this is ever populated? There should be changes to the MessageProcessor to get the update type out of the message metadata but I can't see it?

2022-08-01 13:37 UTC, jhevans commented on src/main/java/uk/gov/justice/probation/courtcasematcher/model/domain/Hearing.java
> +    private final String hearingEventType;
It looks like this hasn't been passed in from CHER, sorry should have spotted that.

2022-08-03 07:17 UTC, jhevans submitted a review, later dismissed

2022-08-03 15:13 UTC, vb-moj commented
Sorry, Missed the judicial result on CPOffence.java. working on it.

2022-08-03 15:13 UTC, closed without merging